/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.vistas;

import javax.swing.JFrame;
import interfaces.IControladorVentanaPrincipal;

public class VentanaPrincipal extends JFrame {
    private IControladorVentanaPrincipal controlador;

    /**
     * Constructor
     * @param controlador controlador de la ventana
     */
    public VentanaPrincipal(IControladorVentanaPrincipal controlador) {
        initComponents();
        this.controlador = controlador;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnItems = new javax.swing.JButton();
        btnOrdenes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repositorios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ventanaAlCerrar(evt);
            }
        });

        btnClientes.setMnemonic('C');
        btnClientes.setText("Clientes");
        btnClientes.setEnabled(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auxiliares/Empleados.jpg"))); // NOI18N
        btnEmpleados.setMnemonic('E');
        btnEmpleados.setText("Empleados");
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosClic(evt);
            }
        });

        btnItems.setMnemonic('I');
        btnItems.setText("Items");
        btnItems.setEnabled(false);
        btnItems.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnItems.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auxiliares/Ordenes.jpg"))); // NOI18N
        btnOrdenes.setMnemonic('O');
        btnOrdenes.setText("Ordenes");
        btnOrdenes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdenes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenesClic(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnItems, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosClic
        this.controlador.btnEmpleadosClic(evt);
    }//GEN-LAST:event_btnEmpleadosClic

    private void btnOrdenesClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenesClic
        this.controlador.btnOrdenesClic(evt);
    }//GEN-LAST:event_btnOrdenesClic

    private void ventanaAlCerrar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ventanaAlCerrar
        this.controlador.ventanaAlCerrar(evt);
    }//GEN-LAST:event_ventanaAlCerrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnItems;
    private javax.swing.JButton btnOrdenes;
    // End of variables declaration//GEN-END:variables
}
